filebrowser/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

filebrowser/forms.py
# coding: utf-8

# imports
import re, os

# django imports
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext as _

# filebrowser imports
from filebrowser.settings import MAX_UPLOAD_SIZE, FOLDER_REGEX
from filebrowser.functions import convert_filename

alnum_name_re = re.compile(FOLDER_REGEX)

class MakeDirForm(forms.Form):
    """
    Form for creating Folder.
    """
    
    def __init__(self, path, *args, **kwargs):
        self.path = path
        super(MakeDirForm, self).__init__(*args, **kwargs)
        
    dir_name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_dir_name(self):
        if self.cleaned_data['dir_name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['dir_name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['dir_name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['dir_name'])


class RenameForm(forms.Form):
    """
    Form for renaming Folder/File.
    """
    
    def __init__(self, path, file_extension, *args, **kwargs):
        self.path = path
        self.file_extension = file_extension
        super(RenameForm, self).__init__(*args, **kwargs)
    
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'New Name'), help_text=_('Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif os.path.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name']) + self.file_extension)):
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

filebrowser/templates/filebrowser/append.html
{% load i18n %}

<div class="module">
    <table>
        <caption>{% trans "FileBrowser" %}</caption>
        <tr class="row2">
            <th scope="row"><a href="{% url fb_browse %}">{% trans "FileBrowser" %}</a></th>
            <td> </td>
            <td> </td>
        </tr>
    </table>
</div>

filebrowser/templates/filebrowser/custom_field.html
{% load fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value }}" />
<a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{% url fb_browse %}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory }}{% endif %}{% if final_attrs.format %}&amp;filter_type={{ final_attrs.format }}{% endif %}');" class="fb_show">
    <img src="{{ final_attrs.search_icon }}" alt="" />
</a>
{% ifequal value.filetype "Image" %}
<p class="help" id="help_{{ final_attrs.id }}">
    <a href="{{ value.url_full }}" target="_blank" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" src="{% version value.path final_attrs.ADMIN_THUMBNAIL %}" class="preview" />
    </a>
</p>
{% else %}
<p class="help" id="help_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endifequal %}
{% if final_attrs.DEBUG %}
<p>
    <strong>Path</strong> {{ value.path }}<br />
    <strong>FileType</strong> {{ value.filetype }}<br /><br />
    <strong>Directory</strong> {{ final_attrs.directory }}<br />
    <strong>Extensions</strong> {{ final_attrs.extensions }}<br />
    <strong>Format</strong> {{ final_attrs.format }}
</p>
{% endif %}

filebrowser/templates/filebrowser/index.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_pagination %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/changelists.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    
    {% ifequal query.pop '1' %} <!-- FileBrowseField -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_FileBrowseField.js"></script>
    {% endifequal %}
    
    {% ifequal query.pop '2' %} <!-- TinyMCE -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_TINYMCE }}tiny_mce_popup.js"></script>
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_TinyMCE.js"></script>
    {% if query.mce_rdomain %}<script language="javascript">document.domain = "{{ query.mce_rdomain }}"</script>{% endif %}
    {% endifequal %}
    
    {% ifequal query.pop '3' %} <!-- CKeditor (former "FCKeditor") -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_CKEditor.js"></script>
    {% endifequal %}
    
    {{ media }}
    
    {% if not actions_on_top and not actions_on_bottom %}
    <style>
        #changelist table thead th:first-child { width: inherit; }
    </style>
    {% endif %}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    {% block object-tools %}
    <ul class="object-tools">
        <li><a href="{% url fb_mkdir %}{% query_string '' 'p' %}">{% trans "New Folder" %}</a></li>
        <li><a href="{% url fb_upload %}{% query_string '' 'p' %}" class="focus">{% trans "Upload" %}</a></li>
    </ul>
    {% endblock %}
    <div class="module filtered" id="changelist">
      {% include "filebrowser/include/toolbar.html" %}
        <div class="changelist-content">
            <div class="result-list-container">
                {% if results_var.results_current %}
                <div class="result-list">
                    <table cellspacing="0">
                        {% include "filebrowser/include/tableheader.html" %}
                        <tbody>
                        {% include "filebrowser/include/filelisting.html" %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
                {% pagination %}
            </div>
        </div>
        <div id="changelist-filter">
            {% include "filebrowser/include/filter.html" %}
        </div>
    </div>
</div>
{% endblock %}

filebrowser/templates/filebrowser/makedir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_csrf %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form action="{% query_string '' 'p' %}" method="post">{% fb_csrf_token %}
    <div>
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
        <div class="form-row {% if form.dir_name.errors %}errors{% endif %}">
            {% if form.dir_name.errors %}<ul class="errorlist">{{ form.dir_name.errors }}</ul>{% endif %}
            <label class="required" for="id_dir_name">{{ form.dir_name.label }}</label>
            {{ form.dir_name }}
            <p class="help">
                {{ form.dir_name.help_text|safe }}
                {% if settings_var.CONVERT_FILENAME %}<br />{% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}{% endif %}
            </p>
        </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% trans 'Submit' %}" class="default" /><br class="clear" />
        </div>
    </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/rename.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_csrf %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% fb_csrf_token %}
    <div>
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
        <div class="form-row {% if form.dir_name.errors %}errors{% endif %}">
            {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
            <label class="required" for="id_dir_name">{{ form.name.label }}</label>
            {{ form.name }}
            {% if file_extension %}<b>{{ file_extension }}</b>{% endif %}
            {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
        </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% trans 'Submit' %}" class="default" />
        </div>
    </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/upload.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="../../jsi18n/"></script>
    <script type="text/javascript" src="{% admin_media_prefix %}js/core.js"></script>

    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery.uploadify.v2.1.0.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/swfobject.js"></script>
    <script type="text/javascript" src="{% admin_media_prefix %}js/admin/CollapsedFieldsets.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        $('#id_file').uploadify({
            'uploader'          : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.swf',
            'script'            : '{% url fb_do_upload %}',
            'scriptData'        : {'session_key': '{{session_key}}'},
            'checkScript'       : '{% url fb_check %}',
            'cancelImg'         : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/cancel.png',
            'auto'              : false,
            'folder'            : '{{ query.dir }}',
            'multi'             : true,
            'fileDesc'          : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
            'fileExt'           : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
            'sizeLimit'         : {{ settings_var.MAX_UPLOAD_SIZE }},
            'scriptAccess'      : 'sameDomain',
            'queueSizeLimit'    : 50,
            'simUploadLimit'    : 1,
            'width'             : 300,
            'height'            : 30,
            'hideButton'        : false,
            'wmode'             : 'transparent',
            translations        : {
                                  browseButton: '{% trans "BROWSE" %}',
                                  error: '{% trans "An Error occured" %}',
                                  completed: '{% trans "Completed" %}',
                                  replaceFile: '{% trans "Do you want to replace the file" %}',
                                  unitKb: '{% trans "KB" %}',
                                  unitMb: '{% trans "MB" %}'
            }
        });
        $('input:submit').click(function(){
            $('#id_file').uploadifyUpload();
            return false;
        });
    });
    </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form>
    <div>
        <fieldset class="module aligned">
        <div class="form-row">
            <input type="File" id="id_file" />
        </div>
        </fieldset>
        
        <fieldset class="module aligned collapse-closed">
        <h2>{% trans "Help" %}</h2>
        <div class="form-row" >
            {% for extension in settings_var.EXTENSIONS.items %}
            {% ifnotequal extension.0 'Folder' %}
            <label class="required">{% if forloop.first %}{% trans "Allowed" %}:{% else %}&nbsp;{% endif %}</label> 
            <p>{{ extension.0|safe }} ({{ extension.1|join:", "|safe }})</p>
            {% endifnotequal %}
            {% endfor %}
        </div>
        <div class="form-row" >
            <label class="required">{% trans "Max. Filesize" %}:</label>
            <p>{{ settings_var.MAX_UPLOAD_SIZE|filesizeformat }}</p>
        </div>
        {% if settings_var.CONVERT_FILENAME %}
        <div class="form-row" >
            <label class="required">&nbsp;</label>
            <p>
                {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
            </p>
        </div>
        {% endif %}
        </fieldset>
        
        <div class="submit-row">
            <p class="deletelink-box">
                <a class="deletelink" href="javascript:$('#id_file').uploadifyClearQueue()">{% trans "Clear Queue" %}</a>
            </p>
            <input class="default" type="submit" name="_save" value='{% trans "Upload" %}' />
        </div>
        
    </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/versions.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_versions %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/changelists.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
    {% if query.pop %}
    <style type="text/css">
        #header { display: none; }
    </style>
    {% endif %}
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    
    {% ifequal query.pop '1' %}
    <!-- FileBrowseField -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_FileBrowseField.js"></script>
    {% endifequal %}
    
    {% ifequal query.pop '2' %}
    <!-- TinyMCE -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_TINYMCE }}tiny_mce_popup.js"></script>
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_TinyMCE.js"></script>
    {% if query.mce_rdomain %}<script language="javascript">document.domain = "{{ query.mce_rdomain }}"</script>{% endif %}
    {% endifequal %}
    
    {% ifequal query.pop '3' %}
    <!-- CKeditor (former "FCKeditor") -->
    <script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_CKEditor.js"></script>
    {% endifequal %}
    
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-list filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <div class="module" id="changelist">
        <div class="changelist-content">
        <table cellspacing="0">
            <thead>
                <tr>
                
                <!-- Select -->
                {% ifequal query.pop '1' %}<th></th>{% endifequal %}
                {% ifequal query.pop '2' %}<th></th>{% endifequal %}
                {% ifequal query.pop '3' %}<th></th>{% endifequal %}
                
                <!-- Filename/Dimensions  -->
                <th>{% trans 'Name' %}</th>
                
                <!-- Version -->
                <th>{% trans 'Image Version' %}</th>
                
                <!-- Debug -->
                {% if settings_var.DEBUG %}<th>{% trans "Debug" %}</th>{% endif %}
                
                </tr>
            </thead>
            <tbody>
            {% for version in settings_var.ADMIN_VERSIONS %}
                {% version_object original version as image_version %}
                <tr class="{% cycle 'row1' 'row2' %}">
                
                <!-- Fileselect for FileBrowseField -->
                {% ifequal query.pop '1' %}
                <td class="fb_icon">
                    {% selectable image_version.filetype query.type %}
                    {% if selectable %}
                    <a href="javascript://" onclick="FileSubmit('{{ image_version.url_save }}', '{{ image_version.url_thumbnail }}', '{{ image_version.filetype }}');" class="fb_selectlink" title="{% trans 'Select' %}"></a>
                    {% else %}
                    <img src="{{ settings_var.URL_FILEBROWSER_MEDIA }}img/filebrowser_icon_select_disabled.gif" width="23" height="17" />
                    {% endif %}
                </td>
                {% endifequal %}
                
                <!-- Fileselect for RTE/TinyMCE -->
                {% ifequal query.pop '2' %}
                <td class="fb_icon">
                    {% selectable image_version.filetype query.type %}
                    {% if selectable %}
                    <a href="javascript:FileBrowserDialogue.fileSubmit('{{ image_version.url_save|escapejs }}');" class="fb_selectlink" title="{% trans 'Select File' %}"></a>
                    {% else %}
                    <img src="{{ settings_var.URL_FILEBROWSER_MEDIA }}img/filebrowser_icon_select_disabled.gif" width="23" height="17" />
                    {% endif %}
                </td>
                {% endifequal %}
                
                <!-- Fileselect for CKeditor (former "FCKeditor") -->
                {% ifequal query.pop '3' %}
                <td class="fb_icon">
                    {% selectable image_version.filetype query.type %}
                    {% if selectable %}
                    <a href="#" onclick="OpenFile(ProtectPath('{{ image_version.url_save|escapejs }}'));return false;" class="fb_selectlink" title="{% trans 'Select File' %}"></a>
                    {% else %}
                    <img src="{{ settings_var.URL_FILEBROWSER_MEDIA }}img/filebrowser_icon_select_disabled.gif" width="23" height="17" />
                    {% endif %}
                </td>
                {% endifequal %}
                
                <!-- Filename / Dimensions  -->
                <td>
                    {% version_setting version %}
                    <strong>{{ version_setting.verbose_name }}</strong><br />
                    {% if version_setting.width %}{% trans "Width" %}: {{ version_setting.width }}px<br />{% endif %}
                    {% if version_setting.height %}{% trans "Height" %}: {{ version_setting.height }}px{% endif %}
                </td>
                
                <!-- Version -->
                <th><img src="{{ image_version.url_full }}" /></th>
                
                <!-- Debug -->
                {% if settings_var.DEBUG %}
                <td>
                    <strong>Filename</strong> {{ image_version.filename }}<br />
                    <strong>Filetype</strong> {{ image_version.filetype }}<br />
                    <strong>Filesize</strong> {{ image_version.filesize }}<br />
                    <strong>Extension</strong> {{ image_version.extension }}<br />
                    <strong>Date</strong> {{ image_version.date }}<br />
                    <strong>Datetime Object</strong> {{ image_version.datetime }}<br /><br />
                    
                    <strong>Relative Path</strong> {{ image_version.path_relative }}<br />
                    <strong>Full Path</strong> {{ image_version.path_full }}<br />
                    <strong>Relative URL</strong> {{ image_version.url_relative }}<br />
                    <strong>Full URL</strong> {{ image_version.url_full }}<br /><br />
                    
                    <strong>URL for FileBrowseField</strong> {{ image_version.url_save }}<br />
                    <strong>Thumbnail URL</strong> {{ image_version.url_thumbnail }}<br /><br />
                    
                    <strong>Dimensions</strong> {{ image_version.dimensions }}<br />
                    <strong>Width</strong> {{ image_version.width }}<br />
                    <strong>Height</strong> {{ image_version.height }}<br />
                    <strong>Orientation</strong> {{ image_version.orientation }}
                </td>
                {% endif %}
                
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}